"""Change tables

Revision ID: 049480272df5
Revises: ebe3a5e7548e
Create Date: 2016-01-03 22:54:09.229213

"""

# revision identifiers, used by Alembic.
revision = '049480272df5'
down_revision = 'ebe3a5e7548e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alt_title', sa.String(), nullable=True),
    sa.Column('isbn10', sa.String(), nullable=True),
    sa.Column('isbn13', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aka', sa.String(), nullable=True),
    sa.Column('alt', sa.String(), nullable=True),
    sa.Column('mobile_url', sa.String(), nullable=True),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('douban_site', sa.String(), nullable=True),
    sa.Column('pubdates', sa.String(), nullable=True),
    sa.Column('mainland_pubdate', sa.String(), nullable=True),
    sa.Column('pubdate', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('durations', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('countries', sa.String(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('seasons_count', sa.Integer(), nullable=True),
    sa.Column('current_season', sa.Integer(), nullable=True),
    sa.Column('schedule_url', sa.String(), nullable=True),
    sa.Column('trailer_urls', sa.String(), nullable=True),
    sa.Column('clip_urls', sa.String(), nullable=True),
    sa.Column('blooper_urls', sa.String(), nullable=True),
    sa.Column('photos', sa.String(), nullable=True),
    sa.Column('popular_reviews', sa.String(), nullable=True),
    sa.Column('playable', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('sort', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collect_count', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('do_count', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('original_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ratings_count', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wish_count', sa.String(), nullable=True))
        batch_op.drop_column('sort')
        batch_op.drop_column('playable')
        batch_op.drop_column('type_')
        batch_op.drop_column('tag')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('type_', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('playable', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('sort', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('wish_count')
        batch_op.drop_column('type')
        batch_op.drop_column('summary')
        batch_op.drop_column('ratings_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('original_title')
        batch_op.drop_column('images')
        batch_op.drop_column('image')
        batch_op.drop_column('do_count')
        batch_op.drop_column('collect_count')

    op.drop_table('movies')
    op.drop_table('books')
    ### end Alembic commands ###
