"""Add thumbnail_xx column

Revision ID: 15c923f77321
Revises: 8d11a68a425c
Create Date: 2016-02-12 21:04:11.729078

"""

# revision identifiers, used by Alembic.
revision = '15c923f77321'
down_revision = '8d11a68a425c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_photos', sa.String(), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('covers', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_covers', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_covers')
        batch_op.drop_column('covers')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_photos')

    ### end Alembic commands ###
