"""video table add total_count column

Revision ID: 2e43193729c3
Revises: ae347beeb622
Create Date: 2016-02-24 23:09:35.627653

"""

# revision identifiers, used by Alembic.
revision = '2e43193729c3'
down_revision = 'ae347beeb622'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_count', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('total_count')

    ### end Alembic commands ###
