"""Movie table add wallpapers column

Revision ID: 528974f52426
Revises: 15c923f77321
Create Date: 2016-02-12 21:17:44.148069

"""

# revision identifiers, used by Alembic.
revision = '528974f52426'
down_revision = '15c923f77321'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_wallpapers', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('wallpapers', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('wallpapers')
        batch_op.drop_column('thumbnail_wallpapers')

    ### end Alembic commands ###
