"""Celebrities add thumbnail column

Revision ID: 68a44fdf586d
Revises: 528974f52426
Create Date: 2016-02-13 20:49:02.275592

"""

# revision identifiers, used by Alembic.
revision = '68a44fdf586d'
down_revision = '528974f52426'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_cover', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_photos', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_photos')
        batch_op.drop_column('thumbnail_cover')

    ### end Alembic commands ###
