"""Add and change name some association table

Revision ID: 8d11a68a425c
Revises: b40e98201e45
Create Date: 2016-01-21 22:28:02.513805

"""

# revision identifiers, used by Alembic.
revision = '8d11a68a425c'
down_revision = 'b40e98201e45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movie_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movie_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects_actors_association',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], )
    )
    op.create_table('subjects_directors_association',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], )
    )
    op.create_table('subjects_playwrights_association',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], )
    )
    op.create_table('movies_countries_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_country_id'], ['movie_countries.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    op.create_table('movies_genres_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_genre_id'], ['movie_genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    op.create_table('movies_languages_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['movie_language_id'], ['movie_languages.id'], )
    )
    op.drop_table('subjects_actors')
    op.drop_table('subjects_directors')
    op.drop_table('subjects_playwrights')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('genres')
        batch_op.drop_column('countries')
        batch_op.drop_column('types')
        batch_op.drop_column('languages')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('types', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('countries', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(), nullable=True))

    op.create_table('subjects_playwrights',
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('celebrity_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], )
    )
    op.create_table('subjects_directors',
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('celebrity_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], )
    )
    op.create_table('subjects_actors',
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('celebrity_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], )
    )
    op.drop_table('movies_languages_association')
    op.drop_table('movies_genres_association')
    op.drop_table('movies_countries_association')
    op.drop_table('subjects_playwrights_association')
    op.drop_table('subjects_directors_association')
    op.drop_table('subjects_actors_association')
    op.drop_table('movie_languages')
    op.drop_table('movie_genres')
    op.drop_table('movie_countries')
    ### end Alembic commands ###
