"""Added account table

Revision ID: a008aa75ec62
Revises: 
Create Date: 2015-12-31 16:09:31.657001

"""

# revision identifiers, used by Alembic.
revision = 'a008aa75ec62'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('cover_x', sa.Integer(), nullable=True),
    sa.Column('cover_y', sa.Integer(), nullable=True),
    sa.Column('playable', sa.Boolean(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('is_beetle_subject', sa.Boolean(), nullable=True),
    sa.Column('rate', sa.String(), nullable=True),
    sa.Column('douban_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    ### end Alembic commands ###
