"""celebrities table add is_detail column

Revision ID: ae347beeb622
Revises: bb7c7b46fba0
Create Date: 2016-02-21 23:38:46.913557

"""

# revision identifiers, used by Alembic.
revision = 'ae347beeb622'
down_revision = 'bb7c7b46fba0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_detail', sa.Boolean(), nullable=True, default=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.drop_column('is_detail')

    ### end Alembic commands ###
