"""Update Celebrities table

Revision ID: b40e98201e45
Revises: 5d376584095d
Create Date: 2016-01-20 15:17:16.112434

"""

# revision identifiers, used by Alembic.
revision = 'b40e98201e45'
down_revision = '5d376584095d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aliases', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('aliases_en', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('family', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('sex')
        batch_op.drop_column('family')
        batch_op.drop_column('aliases_en')
        batch_op.drop_column('aliases')

    ### end Alembic commands ###
