"""Model refactoring

Revision ID: cc825dd0b55a
Revises: 
Create Date: 2016-02-16 01:15:39.952928

"""

# revision identifiers, used by Alembic.
revision = 'cc825dd0b55a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('douban_id', sa.String(), nullable=True),
    sa.Column('douban_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('aliases_en', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('thumbnail_cover', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('born_place', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('professions', sa.String(), nullable=True),
    sa.Column('constellation', sa.String(), nullable=True),
    sa.Column('photos', sa.String(), nullable=True),
    sa.Column('thumbnail_photos', sa.String(), nullable=True),
    sa.Column('imdb_number', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('douban_id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('covers', sa.String(), nullable=True),
    sa.Column('thumbnail_covers', sa.String(), nullable=True),
    sa.Column('pubdate', sa.String(), nullable=True),
    sa.Column('douban_id', sa.String(), nullable=True),
    sa.Column('douban_url', sa.String(), nullable=True),
    sa.Column('cover_x', sa.Integer(), nullable=True),
    sa.Column('cover_y', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('is_beetle_subject', sa.Boolean(), nullable=True),
    sa.Column('douban_rate', sa.String(), nullable=True),
    sa.Column('douban_rating', sa.String(), nullable=True),
    sa.Column('douban_ratings_count', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tv_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alt_title', sa.String(), nullable=True),
    sa.Column('isbn10', sa.String(), nullable=True),
    sa.Column('isbn13', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_actors_association',
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['media.id'], )
    )
    op.create_table('media_countries_association',
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('medium_country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['media.id'], )
    )
    op.create_table('media_directors_association',
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['media.id'], )
    )
    op.create_table('media_languages_association',
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('medium_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medium_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['medium_language_id'], ['languages.id'], )
    )
    op.create_table('media_playwrights_association',
    sa.Column('medium_id', sa.Integer(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.ForeignKeyConstraint(['medium_id'], ['media.id'], )
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('official_site', sa.String(), nullable=True),
    sa.Column('imdb_number', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('current_season', sa.Integer(), nullable=True),
    sa.Column('photos', sa.String(), nullable=True),
    sa.Column('thumbnail_photos', sa.String(), nullable=True),
    sa.Column('wallpapers', sa.String(), nullable=True),
    sa.Column('thumbnail_wallpapers', sa.String(), nullable=True),
    sa.Column('playable', sa.Boolean(), nullable=True),
    sa.Column('crawler_tag', sa.String(), nullable=True),
    sa.Column('crawler_sort', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies_genres_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_genre_id'], ['movie_genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_genres_association')
    op.drop_table('movies')
    op.drop_table('videos')
    op.drop_table('media_playwrights_association')
    op.drop_table('media_languages_association')
    op.drop_table('media_directors_association')
    op.drop_table('media_countries_association')
    op.drop_table('media_actors_association')
    op.drop_table('books')
    op.drop_table('tv_genres')
    op.drop_table('movie_genres')
    op.drop_table('media')
    op.drop_table('languages')
    op.drop_table('countries')
    op.drop_table('celebrities')
    ### end Alembic commands ###
