"""Subjects table add type, tag, sort column

Revision ID: ebe3a5e7548e
Revises: a008aa75ec62
Create Date: 2015-12-31 20:11:46.193678

"""

# revision identifiers, used by Alembic.
revision = 'ebe3a5e7548e'
down_revision = 'a008aa75ec62'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('sort', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('tag', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('type_', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'type_')
    op.drop_column('subjects', 'tag')
    op.drop_column('subjects', 'sort')
    ### end Alembic commands ###
